import type { Config } from "tailwindcss";

const config = {
    darkMode: ["class"],
    content: [
        "./pages/**/*.{ts,tsx}",
        "./components/**/*.{ts,tsx}",
        "./app/**/*.{ts,tsx}",
        "./src/**/*.{ts,tsx}",
        "./content/**/*.{md,mdx}",
    ],
    prefix: "",
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            listStyleType: {
                circle: "circle",
                square: "square",
            },
            colors: {
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                // primary: {
                //   DEFAULT: "hsl(var(--primary))",
                //   foreground: "hsl(var(--primary-foreground))",
                // },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
                primary: "#121212",
                bitcoin: "#FF9900",
                low: "#7EFF00",
                medium: "#FFC21B",
                high: "#EC0B43",
                critical: "#A50F11",
                lightsecondary: "#e5ebeb",
                lighttertiary: "#CECECA",
                lighttableheader: "#736F72",
                text_table_row: "#363534",
                text_table_header: "#0A0D12",
                table_header: "#F5F8FD",
                brand: "#FE4F18",
                brand_fill: "#F4F7FA",
                brand_neutral: "3C3D41",
                bg_primary: "#FDFDFD",
                bg_secondary: "F5F8FD",
                bg_tertiary: "FFFFFF",
                icon_primary: "#292929",
                icon_secondary: "#434D65",
                icon_tertiary: "#C9D0D8",
                icon_quaternary: "#F4F7FA",
                state_default: "#FDFDFD",
                state_hover: "#F5F8FD",
                state_brand: "#FFF4ED",
                stroke_brand: "#FE4F18",
                stroke_primary: "#767B8F",
                stroke_secondary: "#D3DDE8",
                stroke_tertiary: "#E1EAF8",
                text_header: "#292929",
                text_primary: "#434D65",
                text_secondary: "#767B8F",
                text_tertiary: "#D3DDE8",
                text_quaternary: "#F5F7F8",
            },
            fontFamily: {
                header: ["Montserrat", "sans-serif"],
                body: ["Public Sans", "sans-serif"],
                playfair: ["Playfair Display", "serif"],
                public: ["Public Sans", "sans-serif"],
                "playfair-display": "Playfair Display",
                hack: "Hack",
                "public-sans": "Public Sans",
                inter: ["Inter", "sans-serif"],
            },
            fontSize: {
                xs: "0.75rem",
                sm: "0.875rem",
                base: "1rem",
                lg: "1.125rem",
                xl: "1.25rem",
                "2xl": "1.5rem",
                "3xl": "1.875rem",
                "4xl": "2rem",
                "5xl": "2.25rem",
                "6xl": "3rem",
                "7xl": "3.75rem",
                "8xl": "4rem",
                "9xl": "4.5rem",
                "10xl": "5rem",
                "11xl": "6rem",
                "12xl": "6.5rem",
                "13xl": "8rem",
                "14xl": "9.75rem",
            },
            boxShadow: {
                "Box Shadow/shadow-sm": "0px 1px 2px 0px rgba(0,0,0,0.05)",
                "Box Shadow/shadow":
                    "0px 1px 3px 0px rgba(0,0,0,0.1), 0px 1px 2px -1px rgba(0,0,0,0.1)",
                "Box Shadow/shadow-md":
                    "0px 4px 6px -1px rgba(0,0,0,0.1), 0px 2px 4px -2px rgba(0,0,0,0.1)",
                "Box Shadow/shadow-lg":
                    "0px 10px 15px -3px rgba(0,0,0,0.1), 0px 4px 6px -4px rgba(0,0,0,0.1)",
                "Box Shadow/shadow-xl":
                    "0px 20px 25px -5px rgba(0,0,0,0.1), 0px 8px 10px -6px rgba(0,0,0,0.1)",
                "Box Shadow/shadow-2xl": "0px 25px 50px -12px rgba(0,0,0,0.25)",
                "Box Shadow/shadow-inner":
                    "inset 0px 2px 4px 0px rgba(0,0,0,0.05)",
                "Blur/blur-none": "",
                "Blur/blur-sm": "",
                "Blur/blur": "",
                "Blur/blur-md": "",
                "Blur/blur-lg": "",
                "Blur/blur-xl": "",
                "Blur/blur-2xl": "",
                "Blur/blur-3xml": "",
                "Backdrop Blur/backdrop-blur-none": "",
                "Backdrop Blur/backdrop-blur-sm": "",
                "Backdrop Blur/backdrop-blur": "",
                "Backdrop Blur/backdrop-blur-md": "",
                "Backdrop Blur/backdrop-blur-lg": "",
                "Backdrop Blur/backdrop-blur-xl": "",
                "Backdrop Blur/backdrop-blur-2xl": "",
                "Backdrop Blur/backdrop-blur-3xl": "",
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
                "rounded-0": "0rem",
                "rounded-1": "0.046875rem",
                "rounded-2": "0.05181884765625rem",
                "rounded-3": "0.08500000089406967rem",
                "rounded-4": "0.125rem",
                "rounded-5": "0.15088024735450745rem",
                "rounded-6": "0.25rem",
                "rounded-7": "0.30029296875rem",
                "rounded-8": "0.3125rem",
                "rounded-9": "0.375rem",
                "rounded-10": "0.5rem",
                "rounded-11": "0.75rem",
                "rounded-12": "0.8291015625rem",
                "rounded-13": "0.9186390042304993rem",
                "rounded-14": "1rem",
                "rounded-15": "1.0416666269302368rem",
                "rounded-16": "1.10546875rem",
                "rounded-17": "1.25rem",
                "rounded-18": "1.3333333730697632rem",
                "rounded-19": "1.4375rem",
                "rounded-20": "1.4739583730697632rem",
                "rounded-21": "1.5rem",
                "rounded-22": "2rem",
                "rounded-23": "2.5rem",
                "rounded-24": "3.625rem",
                "rounded-25": "3.875rem",
                "rounded-26": "4rem",
                "rounded-27": "62.4375rem",
            },
            keyframes: {
                "accordion-down": {
                    from: {
                        height: "0",
                    },
                    to: {
                        height: "var(--radix-accordion-content-height)",
                    },
                },
                "accordion-up": {
                    from: {
                        height: "var(--radix-accordion-content-height)",
                    },
                    to: {
                        height: "0",
                    },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        },
    },
    plugins: [
        require("tailwindcss-animate"),
        require("@tailwindcss/typography"),
    ],
} satisfies Config;

export default config;
